language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7 MODELDICT=1.2.0
  - DJANGO=1.3.1 MODELDICT=1.2.0
  - DJANGO=1.4 MODELDICT=1.2.0
  - DJANGO=1.5 MODELDICT=1.2.0
  - DJANGO=1.2.7 MODELDICT=1.4.1
  - DJANGO=1.3.1 MODELDICT=1.4.1
  - DJANGO=1.4 MODELDICT=1.4.1
  - DJANGO=1.5 MODELDICT=1.4.1
install:
  - pip install -q Django==$DJANGO
  - pip install -q django-modeldict==$MODELDICT
  - pip install -q flake8
  - pip install -q -e .
script:
  - make test
