language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7 MODELDICT=1.2.0
  - DJANGO=1.3.1 MODELDICT=1.2.0
  - DJANGO=1.4 MODELDICT=1.2.0
  - DJANGO=1.5 MODELDICT=1.2.0
  - DJANGO=1.2.7 MODELDICT=1.4.1
  - DJANGO=1.3.1 MODELDICT=1.4.1
  - DJANGO=1.4 MODELDICT=1.4.1
  - DJANGO=1.5 MODELDICT=1.4.1
install:
  - pip install  Django==$DJANGO
  - pip install  django-modeldict==$MODELDICT
  - pip install  flake8
  - pip install  -e .
script:
  - make test
